@startuml User_Object
skinparam monochrome true
skinparam linetype ortho

' Instancia de la Entidad Principal
object "usuarioGabriel : User" as user

' Instancias de los Value Objects
object "id : UserId" as userId {
  value = "usr-8f7d9a2b"
}

object "name : UserName" as userName {
  value = "Gabriel"
}

object "email : UserEmail" as userEmail {
  value = "gabriel@example.com"
}

object "password : UserPassword" as userPassword {
  value = "Secreta123!"
}

object "roles : UserRoles" as userRoles {
  value = ["Guerrero"]
}

object "createdAt : UserCreatedAt" as userCreatedAt {
  value = Date("2026-04-07T10:00:00Z")
}

object "fechaNacimiento : UserFechaNacimiento" as userFechaNacimiento {
  value = Date("1995-10-15T00:00:00Z")
}

' Relaciones que muestran cómo la entidad agrupa a los objetos
user *-- userId : _id
user *-- userName : _name
user *-- userEmail : _email
user *-- userPassword : _password
user *-- userRoles : _roles
user *-- userCreatedAt : _createdAt
user *-- userFechaNacimiento : _fechaNacimiento

@enduml