import type { NotificationItem } from '../types/types';

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    type: 'alert',
    title: 'Alerta de glucosa',
    message: 'Tu nivel de glucosa está alto: 180 mg/dL',
    link: '/bitacora/control-glucosa',
    read: false,
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: '2',
    type: 'reminder',
    title: 'Recordatorio de insulina',
    message: 'Es hora de tu dosis de insulina rápida',
    link: '/bitacora/dosis-insulina',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: '3',
    type: 'achievement',
    title: 'Logro desbloqueado',
    message: '¡Has obtenido la insignia "Escudo de Fibra"!',
    link: '/agente/camino',
    read: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: '4',
    type: 'warning',
    title: 'Hipoglucemia detectada',
    message: 'Tu glucosa bajó a 65 mg/dL. Revisa tu estado.',
    link: '/bitacora/control-glucosa',
    read: true,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: '5',
    type: 'info',
    title: 'Registro pendiente',
    message: 'No has registrado tu peso hoy. ¡Mantén tu bitácora al día!',
    link: '/bitacora/monitoreo-fisico',
    read: false,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: '6',
    type: 'reminder',
    title: 'Prueba de HbA1c',
    message: 'Recuerda realizarte tu examen de hemoglobina glucosilada',
    link: '/bitacora/control-glucosa',
    read: true,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: '7',
    type: 'achievement',
    title: 'Racha de 7 días',
    message: '¡7 días consecutivos en zona segura! Sigue así.',
    link: '/perfil',
    read: false,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];
